### ISSUE TITLE
Rewrite README.md

### ISSUE THREAD

**Issue by pydanny** [margaritahumanitarian/laptopsforfamilies.org#13]
Right now it is focused on tailwind rather than the mission of this site: getting laptops to students in need. See the README at https://github.com/margaritahumanitarian/helpafamily for an example

**Comment by akshitarora921** [comment]
Hi, Can I work on this?

**Comment by akshitarora921** [comment]
Do we need to delete other sections also? 
- Creator
- Image Attribution
- Copyright and License
- The default branch has been renamed!

**Comment by audreyfeldroy** [comment]
Great question @akshitarora921. I left those out of the task list because it's nice to give attribution to the upstream project, so you can leave the first 3 of those in. If they cause confusion or take up too much space, you can experiment with combining them into an "Attribution" section. The 4th can be deleted.
